project:
  type: website
  output-dir: docs

website:
  title: "QTM_350_Assignment_5"
  navbar:
    pinned: true
    left:
      - href: Assignment_5.qmd
        text: Report
      - href: presentation.qmd
        text: Presentation

format:
  html:
    theme: 
      light: lumen
      dark: solar
    css: styles.css
    toc: true
